### ISSUE TITLE
Compatibility with AGORA

### ISSUE THREAD

**Issue by arianccbasile** [cdanielmachado/smetana#21]
Dear Daniel,
I was trying to run SMETANA on some models of the AGORA2 collection but I get error. 
Can you suggest the parameters to run it. 

Best,
Arianna

**Comment by cdanielmachado** [comment]
Hi Arianna,

Can you copy-paste the error? 

Best regards,
Daniel

**Comment by arianccbasile** [comment]
Dear Daniel, 
I was running "smetana *.xml --flavor cobra" getting the following error:
```
Traceback (most recent call last):
  File "/home/bioinfo/anaconda3/envs/py36/bin/smetana", line 106, in <module>
    ignore_coupling=args.no_coupling,
  File "/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/smetana/interface.py", line 338, in main
    medium_id, env = define_environment(medium, media_db, community, mode, verbose, min_mol_weight, use_lp)
  File "/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/smetana/interface.py", line 115, in define_environment
    env = Environment.complete(community.merged, max_uptake=max_uptake)
  File "/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/smetana/legacy.py", line 203, in merged
    self._merged_model = self.generate_merged_model()
  File "/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/smetana/legacy.py", line 271, in generate_merged_model
    models_missing_biomass = [m.id for m in self._organisms.values() if not m.biomass_reaction]
  File "/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/smetana/legacy.py", line 271, in <listcomp>
    models_missing_biomass = [m.id for m in self._organisms.values() if not m.biomass_reaction]
  File "/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/reframed/core/cbmodel.py", line 190, in biomass_reaction
    self._detect_biomass_reaction()
  File "/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/reframed/core/cbmodel.py", line 213, in _detect_biomass_reaction
    raise RuntimeError(f"No biomass reaction identified from model objective.")
RuntimeError: No biomass reaction identified from model objective.
```
Now I tried "smetana *.xml --flavor fbc2" and it seems working, the only problem is that I get a bunch of warnings like:

```
UserWarning: Gene association for reaction R_MALDC is not DNF
  warn(f"Gene association for reaction {reaction_id} is not DNF")
/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/reframed/io/sbml.py:510: UserWarning: Gene association for reaction R_FE3t4 is not DNF
  warn(f"Gene association for reaction {reaction_id} is not DNF")
/home/bioinfo/anaconda3/envs/py36/lib/python3.6/site-packages/reframed/core/cbmodel.py:211: UserWarning: Suspicious biomass identifier: R_bio1
  warn(f"Suspicious biomass identifier: {self._biomass_reaction}")
```

**Comment by cdanielmachado** [comment]
Perfect. Don't worry about those warnings, they won't affect the simulation results.

**Comment by EdwinMosesAppiah** [comment]
Dear Daniel, 

My smetana fails to calculate the MIP score and returns N/A.
I am using the AGORA 2 model.
Below is the warning messages

 MIP: Failed to find a valid solution for non-interacting community
  warn('MIP: Failed to find a valid solution for non-interacting community
  
  Could you help me circumvent this problem?
