### ISSUE TITLE
issues when add -c communities

### ISSUE THREAD

**Issue by qikongwanli** [cdanielmachado/smetana#37]
$ smetana *.xml -c community.txt
Traceback (most recent call last):
  File "/home/qing/miniconda3/envs/metaGEM/bin/smetana", line 106, in <module>
    ignore_coupling=args.no_coupling,
  File "/home/qing/miniconda3/envs/metaGEM/lib/python3.6/site-packages/smetana/interface.py", line 333, in main
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/home/qing/miniconda3/envs/metaGEM/lib/python3.6/site-packages/smetana/interface.py", line 333, in <listcomp>
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/home/qing/miniconda3/envs/metaGEM/lib/python3.6/site-packages/reframed/io/cache.py", line 26, in get_model
    raise RuntimeError("Model not in list: " + model_id)
RuntimeError: Model not in list: B51_0_22bin_38_fa

#my model list
B51_0_22bin_14_fa.xml
B51_0_22bin_29_fa.xml
B51_0_22bin_38_fa.xml
B51_0_22bin_60_fa.xml

#commutities
community1	B51_0_22bin_14_fa
community1	B51_0_22bin_29_fa
community2	B51_0_22bin_38_fa
community2	B51_0_22bin_60_fa
community2	B51_0_22bin_29_fa

**Comment by cdanielmachado** [comment]
That's strange, everything seems to be correct. Are the models in the same folder where you are executing this command? What is the output of `ls *.xml` ?

**Comment by qikongwanli** [comment]
> That's strange, everything seems to be correct. Are the models in the same folder where you are executing this command? What is the output of `ls *.xml` ?

Hi Daniel,
I am sure that all the models are in the same folder.
