### ISSUE TITLE
Specifying compartment identifiers

### ISSUE THREAD

**Issue by xlmf** [cdanielmachado/smetana#40]
Hi,
I am currently trying to run smetana on some genome-scale metabolic models constructed using ModelSEED. 
I get an error when trying to run smetana through the command `smetana *.xml`, so I checked that my models are valid SBML files using the online SBML validator. My models are valid, but there seems to be a problem with the compartment identifiers. The warning from the validator says:

"As a principle of best modeling practice, the size of a <compartment> should be set to a value rather than be left undefined. Doing so improves the portability of models between different simulation and analysis systems, and helps make it easier to detect potential errors in models. The <compartment> with the id 'c0' does not have a 'size' attribute, nor is its initial value set by an <initialAssignment> or <assignmentRule>. 

<compartment id="c0" name="Cytosol_0" />
<compartment id="e0" name="Extracellular_0" />"

When I want to specify the identifier of the extracellular compartment in the models by including --ext e0 in my command, I get an error saying that the '--ext e0' argument is not recognized. Also, it doesn't say anything about it in the documentation, but is there a way to specify the identifier of the cytosol, too? 

I think specifying the compartment identifiers could maybe help fixing the error I get when trying to run the program (?):
Traceback (most recent call last):
  File "/home/laura/.local/bin/smetana", line 89, in <module>
    main(
  File "/home/laura/.local/lib/python3.8/site-packages/smetana/interface.py", line 333, in main
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/home/laura/.local/lib/python3.8/site-packages/smetana/interface.py", line 333, in <listcomp>
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/home/laura/.local/lib/python3.8/site-packages/reframed/io/cache.py", line 31, in get_model
    model = load_cbmodel(self.paths[model_id], **self.load_args)
  File "/home/laura/.local/lib/python3.8/site-packages/reframed/io/sbml.py", line 148, in load_cbmodel
    load_metabolites(sbml_model, model, flavor, load_metadata)
  File "/home/laura/.local/lib/python3.8/site-packages/reframed/io/sbml.py", line 220, in load_metabolites
    model.add_metabolite(load_metabolite(species, flavor, load_metadata=load_metadata))
  File "/home/laura/.local/lib/python3.8/site-packages/reframed/io/sbml.py", line 228, in load_metabolite
    if fbc_species.isSetChemicalFormula():
AttributeError: 'NoneType' object has no attribute 'isSetChemicalFormula'

Thank you in advance! :)

Laura

**Comment by vicru93** [comment]
Hi, how did you solve this problem?

**Comment by lauramhfur** [comment]
Hi! I sadly wasn't able to solve the problem :)
