### ISSUE TITLE
Adjusting the non-CarveMe GEMs to SMETANA

### ISSUE THREAD

**Issue by wupeng1998** [cdanielmachado/smetana#41]
Hi, I have a problem finding biomass when I simulate the model built with modelseed using smetana, have you tried how the modelseed model should be modified?

(py38) C:\Users\wupen>python C:\Users\wupen\Program\Anaconda3\envs\py38\Scripts\smetana D:\jupyternotebook\Y_YL_model\ac_final_WP1376_03.xml D:\jupyternotebook\Y_YL_model\st_process_atp_compart.xml  -v -d --molweight --zeros --flavor cobra
Loading community: all
Traceback (most recent call last):
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\Scripts\smetana", line 89, in <module>
    main(
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\smetana\interface.py", line 338, in main
    medium_id, env = define_environment(medium, media_db, community, mode, verbose, min_mol_weight, use_lp)
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\smetana\interface.py", line 118, in define_environment
    env = minimal_environment(community, verbose=verbose, min_mol_weight=min_mol_weight, use_lp=use_lp,
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\smetana\smetana.py", line 373, in minimal_environment
    exch_reactions = set(community.merged.get_exchange_reactions())
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\smetana\legacy.py", line 203, in merged
    self._merged_model = self.generate_merged_model()
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\smetana\legacy.py", line 271, in generate_merged_model
    models_missing_biomass = [m.id for m in self._organisms.values() if not m.biomass_reaction]
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\smetana\legacy.py", line 271, in <listcomp>
    models_missing_biomass = [m.id for m in self._organisms.values() if not m.biomass_reaction]
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\reframed\core\cbmodel.py", line 190, in biomass_reaction
    self._detect_biomass_reaction()
  File "C:\Users\wupen\Program\Anaconda3\envs\py38\lib\site-packages\reframed\core\cbmodel.py", line 213, in _detect_biomass_reaction
    raise RuntimeError(f"No biomass reaction identified from model objective.")
RuntimeError: No biomass reaction identified from model objective.

**Comment by vicru93** [comment]
Hi, how did you solve this problem?
