### ISSUE TITLE
AttributeError: issues loading carveme models

### ISSUE THREAD

**Issue by roschlec** [cdanielmachado/smetana#9]
Hi Daniel,
Thanks for all the work you put into developing these tools for metabolic modeling and microbial communities!
I'm trying to use smetana but I encounter the following issue regarding an 'AttributeError':

```

$ smetana model1.xml model2.xml
Traceback (most recent call last):
  File "/home/biol/anaconda2/envs/py3/bin/smetana", line 106, in <module>
    ignore_coupling=args.no_coupling,
  File "/home/biol/anaconda2/envs/py3/lib/python3.7/site-packages/smetana/interface.py", line 333, in main
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/home/biol/anaconda2/envs/py3/lib/python3.7/site-packages/smetana/interface.py", line 333, in <listcomp>
    comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
  File "/home/biol/anaconda2/envs/py3/lib/python3.7/site-packages/reframed/io/cache.py", line 31, in get_model
    model = load_cbmodel(self.paths[model_id], **self.load_args)
  File "/home/biol/anaconda2/envs/py3/lib/python3.7/site-packages/reframed/io/sbml.py", line 147, in load_cbmodel
    load_metabolites(sbml_model, model, flavor, load_metadata)
  File "/home/biol/anaconda2/envs/py3/lib/python3.7/site-packages/reframed/io/sbml.py", line 219, in load_metabolites
    model.add_metabolite(load_metabolite(species, flavor, load_metadata=load_metadata))
  File "/home/biol/anaconda2/envs/py3/lib/python3.7/site-packages/reframed/io/sbml.py", line 227, in load_metabolite
    if fbc_species.isSetChemicalFormula():
AttributeError: 'NoneType' object has no attribute 'isSetChemicalFormula'

```
The models I'm trying to use were built with CarveMe. 

I also tried using the example data (`smetana ec_glc_ko.xml ec_nh4_ko.xml`) and had no issues with calculating the scores.

I appreciate the help!

Thanks,
Rudolf

**Comment by cdanielmachado** [comment]
Hi Rudolf,

Could you please add `--flavor cobra` when running smetana?

This should work, otherwise please let me know.
